In [ ]:
''' 1. Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it
enhance Python's capabilities for numerical operations?'''

ANSWER:

NumPy (Numerical Python) is a powerful library in Python that provides support for large,
multi-dimensional arrays and matrices, along with a collection of mathematical
functions to operate on these arrays efficiently. It serves as the backbone for
many other scientific computing and data analysis libraries.

Purpose of NumPy:
Efficient Numerical Computation: NumPy is designed for high-performance computations
involving arrays and matrices, enabling fast operations on large datasets.

Multi-dimensional Arrays: At the core of NumPy is the ndarray object, which allows
for the creation and manipulation of n-dimensional arrays (1D, 2D, 3D, etc.),
making it easier to work with complex datasets.

Mathematical Functions: NumPy provides a wide range of mathematical operations such
as linear algebra, Fourier transforms, statistical functions, and more, essential
for scientific computing.

Memory-efficient Storage: NumPy arrays consume much less memory than Python’s
built-in data structures (like lists), especially for large datasets.

In [ ]:
'''2. Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the
other?'''

np.mean():

Purpose: Computes the arithmetic mean along the specified axis of the array.
Syntax: np.mean(a, axis=None, dtype=None, out=None, keepdims=False)
a: Input array.
#axis:
 Axis along which the means are computed. By default, it computes the mean
of the flattened array.
#dtype:
Data type to use in computing the mean.
#out:
Alternative output array to place the result.
#keepdims:
If set to True, the axes that are reduced are left in the result as dimensions with size one.


np.average():

Purpose: Computes the weighted average of array elements along the specified axis.
If no weights are provided, it behaves like np.mean().

Syntax: np.average(a, axis=None, weights=None, returned=False)
Parameters:
#a:
Input array.
#axis:
Axis along which the averages are computed. By default, it computes the
average of the flattened array.
#weights:
An optional array of the same shape as a. It specifies the weight for each element.
returned: If set to True, returns a tuple of the average and the sum of the weights.

In [ ]:
'''3. Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D
arrays.'''

ANSWER:

In NumPy, arrays can be reversed along different axes using various techniques.
 Here are some methods for reversing NumPy arrays along different axes:

1. Reversing a 1D NumPy Array
For a 1D array, reversing the array means reversing the order of the elements.
import numpy as np

# Create a 1D array
arr_1d = np.array([1, 2, 3, 4, 5])

# Reverse the 1D array
reversed_1d = arr_1d[::-1]
print(reversed_1d)
# Output: [5 4 3 2 1]

Method 2: Using np.flip()
NumPy’s flip() function reverses the array along the specified axis. For a 1D array, the axis is 0.

reversed_1d_flip = np.flip(arr_1d)
print(reversed_1d_flip)
# Output: [5 4 3 2 1]


In NumPy, arrays can be reversed along different axes using various techniques. Here are some methods for reversing NumPy arrays along different axes:

1. Reversing a 1D NumPy Array
For a 1D array, reversing the array means reversing the order of the elements.

Method 1: Using slicing ([::-1])
You can reverse the array using Python slicing with a step of -1.

python
Copy code
import numpy as np

# Create a 1D array
arr_1d = np.array([1, 2, 3, 4, 5])

# Reverse the 1D array
reversed_1d = arr_1d[::-1]
print(reversed_1d)
Output:

csharp
Copy code
[5 4 3 2 1]
Method 2: Using np.flip()
NumPy’s flip() function reverses the array along the specified axis. For a 1D array, the axis is 0.

python
Copy code
reversed_1d_flip = np.flip(arr_1d)
print(reversed_1d_flip)
Output:

csharp
Copy code
[5 4 3 2 1]

2. Reversing a 2D NumPy Array
For a 2D array, you can reverse the array along different axes: rows, columns, or both.

Method 1: Reverse along rows (axis 0)
To reverse along the rows (top-to-bottom) by slicing ([::-1, :])

# Create a 2D array
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Reverse along rows#
reversed_rows = arr_2d[::-1, :]
print(reversed_rows)
#ouput: [[7 8 9]
        [4 5 6]
        [1 2 3]]


Or using np.flip:
reversed_rows_flip = np.flip(arr_2d, axis=0)
print(reversed_rows_flip)
#ouput:
[[7 8 9]
[4 5 6]
[1 2 3]]




In [ ]:
'''4. How can you determine the data type of elements in a NumPy array?
Discuss the importance of data types
in memory management and performance.'''

Checking the Data Type:

import numpy as np
# Create a NumPy array
arr = np.array([1, 2, 3])
# Determine the data type of elements
print(arr.dtype)

#Output:int64
This shows that the elements in the array are 64-bit integers.

Example: Data Type of Floating-Point Numbers
arr_float = np.array([1.0, 2.0, 3.0])

# Determine the data type
print(arr_float.dtype)

#Output:float64
This shows that the array contains 64-bit floating-point numbers.

Importance of Data Types in NumPy for Memory Management and Performance:

Data types in NumPy are important for efficient memory management.
Each data type has a fixed size in memory. For example:
An int8 (8-bit integer) occupies 1 byte per element.
An int64 (64-bit integer) occupies 8 bytes per element.
A float64 (64-bit floating-point number) also occupies 8 bytes per element.
By choosing the appropriate data type for an array, you can control the memory
footprint of the array. For instance, if you only need small integers, using int8
 instead of int64 can significantly reduce the memory usage, especially for large arrays.


In [ ]:
5.'''Define ndarrays in NumPy and explain their key features.
How do they differ from standard Python lists?'''

An ndarray is the core data structure in NumPy,
representing a homogeneous, multidimensional array of elements.

#Multidimensional:
An ndarray can have any number of dimensions 1D array ,2D array upto nD array
#Homogeneous Data:
All elements in an ndarray must be of the same data type.
#Efficient Memory Layout:
NumPy arrays store elements in contiguous blocks of memory,
making element access and operations much faster compared to Python lists.
#Fixed Size
Once an ndarray is created, its size cannot be changed.
#NumPy allows broadcasting
arr = np.array([1, 2, 3])
result = arr + 1
print(result)   Output: [2, 3, 4]
#Slicing and Indexing
Like Python lists, NumPy arrays support slicing and advanced indexing,
but they extend this functionality to multiple dimensions.


In [ ]:
'''6.Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.'''

1. Memory Efficiency
NumPy Arrays: Store elements in contiguous blocks of memory, making memory
access faster and more efficient. Additionally, NumPy arrays are homogeneous,
meaning all elements are of the same type
Python Lists: Store elements as references to Python objects, which adds overhead.

2. Vectorized Operations (Avoiding Loops)
NumPy Arrays: Support vectorized operations, meaning element-wise operations
are performed directly in C (or Fortran), without needing explicit Python loops.
These operations are optimized and happen much faster because they are executed
at the compiled level.

Python Lists: Require explicit loops for element-wise operations, which are
slower because each iteration is interpreted by the Python interpreter and
involves additional overhead for type-checking and memory allocation.

3.Broadcasting
NumPy Arrays: Support broadcasting, a feature that allows you to perform operations
between arrays of different shapes without needing to explicitly reshape or
replicate data. This reduces the need for looping and additional memory allocation,
making operations both faster and more memory-efficient.
Python Lists: Do not support broadcasting.

4.Numerical Precision and Control over Data Types
NumPy Arrays: Provide control over the data types of the elements allowing you to
optimize both memory usage and performance depending on your requirements. You can work
 with very large datasets with reduced precision if necessary to save memory.
Python Lists: Automatically use the int or float types, which might not always
provide the best performance or memory efficiency.

In [ ]:
'''7.Compare vstack() and hstack() functions in NumPy. Provide examples
demonstrating their usage and output.'''
In NumPy, the functions np.vstack() and np.hstack() are used to stack arrays
vertically and horizontally, respectively.

np.vstack():
Purpose: Stacks arrays vertically (row-wise).
Input Requirement: The input arrays must have the same shape along all but the first axis.
Output: Returns a new array with the input arrays stacked on top of each other.

np.hstack():

Purpose: Stacks arrays horizontally (column-wise).
Input Requirement: The input arrays must have the same shape along all but the second axis.
Output: Returns a new array with the input arrays concatenated side by side.

In [ ]:
'''8.Explain the differences between fliplr() and flipud() methods in NumPy,
including their effects on various
array dimensions.'''

In NumPy, the functions np.fliplr() and np.flipud() are used to flip (reverse)
the elements of an array along different axes. Here’s a detailed explanation of
their differences, including how they affect various array dimensions.

1.
np.fliplr():

Purpose: Flips an array from left to right (horizontal flipping).
Effect: It reverses the order of the columns in a 2D array.
Input Requirement: This function can only be used on 2D arrays (matrices).
For higher dimensions, it will work on the last two dimensions.

2.np.flipud():

Purpose: Flips an array from up to down (vertical flipping).
Effect: It reverses the order of the rows in a 2D array.
Input Requirement: This function can only be used on 2D arrays. Similar to fliplr(),
it will work on the last two dimensions for higher dimensions.

In [ ]:
'''8.9. Discuss the functionality of the array_split() method in NumPy.
How does it handle uneven splits?'''

The np.array_split() function in NumPy is used to split an array into multiple
sub-arrays along a specified axis.

Functionality of np.array_split()

Syntax: numpy.array_split(ary, indices_or_sections, axis=0)
Parameters:
ary: The input array to be split.
indices_or_sections: This can either be:
An integer, indicating the number of equal parts to split the array into.
An array of indices, indicating where to split the array.
axis: The axis along which to split the array (default is 0, i.e., along rows).
Return Value:

It returns a list of sub-arrays after splitting the original array.

In [ ]:
'''10.10. Explain the concepts of vectorization and broadcasting in NumPy.
How do they contribute to efficient array operations?'''

1.Vectorization:
Vectorization refers to the ability to perform operations on entire arrays or
slices of arrays, rather than using explicit loops. In vectorized operations,
NumPy takes advantage of underlying optimized C and Fortran code, enabling faster computations.

Advantages:

Performance: Vectorized operations are typically much faster than their equivalent
operations implemented using Python loops because they use optimized, low-level routines.
Readability: Code that utilizes vectorization is often more concise and easier
to read, as it avoids boilerplate code.
EXAMPLE:

import numpy as np
a = np.random.rand(1000000)
b = np.random.rand(1000000)

# Vectorized addition
c = a -b

2.Broadcasting
Broadcasting is a technique that allows NumPy to work with arrays of different
shapes during arithmetic operations. When performing operations on arrays of different
shapes, NumPy automatically expands the smaller array (in terms of dimensions) to
match the shape of the larger array without making unnecessary copies of the data.

EXAMPLE:

import numpy as np
a = np.array([1, 2, 3])
b = np.array([[10], [20], [30]])

# Broadcasting in action
result = a + b
print(result)
# Output:
[[11]
[22]
[33]]


In [3]:
#PRACTICAL QUESTION:
'''1. Create a 3x3 NumPy array with random integers between 1 and 100.
Then, interchange its rows and columns.'''
import numpy as np
arr=np.random.randint(1,100,(3,3))
print(arr)
arr=arr.T
print("after interchanging: ",arr)

[[94  7 97]
 [71 21 22]
 [ 4 52 96]]
after interchanging:  [[94 71  4]
 [ 7 21 52]
 [97 22 96]]


In [6]:
##PRACTICAL QUESTION:
'''2.Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.'''

import numpy as np
arr=np.random.randint(1,10,(1,10))
print(arr)
print("After reshaping it into a 2x5 array: ",arr.reshape(2,5))
print("After reshaping it into a 5x2 array: ",arr.reshape(5,2))

[[5 8 6 7 1 7 5 1 6 3]]
After reshaping it into a 2x5 array:  [[5 8 6 7 1]
 [7 5 1 6 3]]
After reshaping it into a 5x2 array:  [[5 8]
 [6 7]
 [1 7]
 [5 1]
 [6 3]]


In [12]:
 ##PRACTICAL QUESTION:
 '''Create a 4x4 NumPy array with random float values. Add a border of
 zeros around it, resulting in a 6x6 array.'''

import numpy as np
arr_4x4 = np.random.rand(4, 4)
arr_6x6 = np.pad(arr_4x4, pad_width=1, mode='constant', constant_values=0)
print(arr_6x6)


[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.68060784 0.12588747 0.05410358 0.91747197 0.        ]
 [0.         0.25678801 0.93071226 0.14786883 0.58974351 0.        ]
 [0.         0.37159565 0.68756622 0.68803423 0.53041737 0.        ]
 [0.         0.39809239 0.73898178 0.94421805 0.52105601 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


In [13]:
'''4. Using NumPy, create an array of integers from 10 to 60 with a step of 5.'''
import numpy as np
arr=np.arange(10,61,5)
print(arr)

[10 15 20 25 30 35 40 45 50 55 60]


In [14]:
'''5.Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply
different case transformations
(uppercase, lowercase, title case, etc.) to each element.'''

import numpy as np
arr = np.array(['python', 'numpy', 'pandas'])
uppercase_arr = np.char.upper(arr)
lowercase_arr = np.char.lower(arr)
titlecase_arr = np.char.title(arr)
print("Original array:", arr)
print("Uppercase:", uppercase_arr)
print("Lowercase:", lowercase_arr)
print("Title case:", titlecase_arr)

Original array: ['python' 'numpy' 'pandas']
Uppercase: ['PYTHON' 'NUMPY' 'PANDAS']
Lowercase: ['python' 'numpy' 'pandas']
Title case: ['Python' 'Numpy' 'Pandas']


In [15]:
'''6. Generate a NumPy array of words. Insert a space between each
 character of every word in the array.'''

import numpy as np
words = np.array(['python', 'numpy', 'pandas'])
spaced_words = np.char.join(' ', words)
print(spaced_words)


['p y t h o n' 'n u m p y' 'p a n d a s']


In [16]:
'''7.Create two 2D NumPy arrays and perform element-wise addition, subtraction,
 multiplication, and division.import numpy as np'''

# Create two 2D NumPy arrays
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8, 9], [10, 11, 12]])

# Perform element-wise operations
addition = array1 + array2
subtraction = array1 - array2
multiplication = array1 * array2
division = array1 / array2

# Display the results
print("Array 1:\n", array1)
print("Array 2:\n", array2)
print("Addition:\n", addition)
print("Subtraction:\n", subtraction)
print("Multiplication:\n", multiplication)
print("Division:\n", division)


Array 1:
 [[1 2 3]
 [4 5 6]]
Array 2:
 [[ 7  8  9]
 [10 11 12]]
Addition:
 [[ 8 10 12]
 [14 16 18]]
Subtraction:
 [[-6 -6 -6]
 [-6 -6 -6]]
Multiplication:
 [[ 7 16 27]
 [40 55 72]]
Division:
 [[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]


In [17]:
'''8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.'''

import numpy as np

# Step 1: Create a 5x5 identity matrix
identity_matrix = np.eye(5)

# Step 2: Extract the diagonal elements
diagonal_elements = np.diag(identity_matrix)

# Display the results
print("5x5 Identity Matrix:\n", identity_matrix)
print("Diagonal Elements:", diagonal_elements)


5x5 Identity Matrix:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Diagonal Elements: [1. 1. 1. 1. 1.]


In [19]:
'''9.Generate a NumPy array of 100 random integers between 0 and 1000.
 Find and display all prime numbers in
this array.'''

import numpy as np

# Step 1: Generate a NumPy array of 100 random integers between 0 and 1000
random_integers = np.random.randint(0, 100, size=100)

# Step 2: Define a function to check for prime numbers
def is_prime(n):
    if n <= 1:
        return False
    for i in range(2, int(n**0.5) + 1):
        if n % i == 0:
            return False
    return True
prime_numbers = [num for num in random_integers if is_prime(num)]
print("Random Integers:", random_integers)
print("Prime Numbers:", prime_numbers)


Random Integers: [84 42 66 22 84 48 99 81 96 68 16 64 92 58 48 52 24 94 49 27 48 55 95  1
 11 71 16 27  9 85 80 75 27 61 57 96 22 64 38 73  7 24 68 41 85  1 60 62
 46 22  9 49 60 98  1 70 46 94 94 82 88 42 23 65 53 56 61 21 59  1 84 84
  8 98 88 42 88 20 77  8  7 13 27 62 65 78 67 16 21 54 62  8 87 25 50 63
 53 51 19 28]
Prime Numbers: [11, 71, 61, 73, 7, 41, 23, 53, 61, 59, 7, 13, 67, 53, 19]


In [21]:
'''10.Create a NumPy array representing daily temperatures for a month.
Calculate and display the weekly
averages.'''

import numpy as np
daily_temperatures = np.random.randint(20, 40, size=28)
weekly_temperatures = daily_temperatures.reshape(4, 7)
weekly_averages = np.mean(weekly_temperatures, axis=1)
print("Daily Temperatures for the Month:\n", daily_temperatures)
print("Weekly Averages:\n", weekly_averages)




Daily Temperatures for the Month:
 [32 23 33 27 31 25 39 38 29 27 23 34 39 39 32 34 29 39 20 29 29 25 35 36
 21 38 24 26]
Weekly Averages:
 [30.         32.71428571 30.28571429 29.28571429]
